### PR TITLE
Rename output lib to DiscordRPC

### PR DESCRIPTION
**Pull request by pg9182**

### CODE REVIEW

**Review by GeckoEidechse — APPROVED** [review]
Name matches old version of DiscordRPC DLL
(The reason we want matching names is so that updating Northstar will replace the old DLL)

**Comment by catornot** [comment]
you forgot to add `#![allow(non_snake_case)]` to `lib.rs` to suppress the warning that comes with non snake case module name lol

**Comment by catornot** [comment]
although maybe it is not that important.

**Comment by GeckoEidechse** [comment]
I'd still take a PR for it ;)

I'm allergic to compiler warnings :P

**Comment by catornot** [comment]
the problem with allowing that at the crate level is that other stuff may be named incorrectly by accident since it would be applied to the whole crate. this problem could be solved by creating a sub module/other file and enforcing non snake case in that module/file.

**Pull request merged**
