### PR TITLE
Rewrite for new plugin system

### PR DESCRIPTION
**Pull request by emma-miler**

### CODE REVIEW

**Comment by emma-miler** [comment]
(Most of the LOC in this PR are from including spdlog)

**Comment by GeckoEidechse** [comment]
> (Most of the LOC in this PR are from including spdlog)

(Committing dependencies as code x_x)

**Comment by catornot** [comment]
I grabbed the dll from this [build](https://github.com/R2Northstar/NorthstarDiscordRPC/actions/runs/3560071184) and it didn't work

logs:
```
[*] Loading Northstar
[*] Failed to create a console window, maybe a console already exists?
[18:53:11] [NORTHSTAR] [info] Profile was not found in command line arguments. Using default: R2Northstar
[18:53:11] [PLUGINSYS] [info] Loading resource from library
[18:53:11] [PLUGINSYS] [info] Failed to load library The specified module could not be found.: <- this is probably DiscordRPCV2
[18:53:11] [PLUGINSYS] [info] Loading resource from library
[18:53:11] [PLUGINSYS] [info] Library R2Northstar/plugins\northstar_discord_rpc.dll has no function initializePlugin
[18:53:11] [PLUGINSYS] [info] Loading resource from library
[18:53:11] [PLUGINSYS] [errr] R2Northstar/plugins\r2plugins_test.dll has an incompatible API version number in its manifest
[18:53:11] [PLUGINSYS] [info] Loading resource from library
[18:53:11] [PLUGINSYS] [info] Succesfully loaded R2Northstar/plugins\rrplug_test.dll
[18:53:11] [PLUGINSYS] [info] Loading plugin rrplug_test version 1.0
[18:53:11] [rrplug_test] [info] plugin logging initialized
[18:53:11] [rrplug_test] [info] hello world from rust northstar version 48
[18:53:11] [rrplug_test] [errr] hello world from rust a thread
````

**Comment by GeckoEidechse** [comment]
Closed in favour of #5

**Pull request closed without merging**
